### ISSUE TITLE
Find a tool which sends gcode files to the firmware

### ISSUE THREAD

**Issue by dbenamy** [OSE/CNC-Torch-Table-OSE#15]
Once I get some known working gcode, I'll put it here for use as a test file.

See http://opensourceecology.org/wiki/GcodeCommunications

**Comment by dbenamy** [comment]
Sorry, it loads them ok but when I click "print" it says:

```
Print thread died due to the following error:
Traceback (most recent call last):
  File "pronterface/build/pyi.darwin/pronterface/outPYZ1.pyz/printcore", line 427, in _print
  File "pronterface/build/pyi.darwin/pronterface/outPYZ1.pyz/printcore", line 499, in _sendnext
  File "pronterface/build/pyi.darwin/pronterface/outPYZ1.pyz/printcore", line 523, in _send
  File "pronterface/build/pyi.darwin/pronterface/outPYZ1.pyz/printrun.GCodeAnalyzer", line 74, in Analyze
  File "pronterface/build/pyi.darwin/pronterface/outPYZ1.pyz/printrun.gcoder", line 72, in parse_coordinates
IndexError: string index out of range
```

**Comment by dbenamy** [comment]
Trying w ubuntu 12.04 64bit (in vmware fusion)
git clone https://github.com/kliment/Printrun.git # sticking with master
directions from readme:

```
sudo apt-get install python-serial python-wxgtk2.8 python-pyglet python-tornado python-setuptools python-libxml2 python-gobject avahi-daemon libavahi-compat-libdnssd1 
cd Printrun/
sudo pip install -r requirements_prontserve.txt # should use a virtualenv but it's a scratch vm so i don't care
```

Unplugged and replugged arduino usb. Fusion ask me where to connect and I said linux.

```
sudo python pronterface.py
```

It failed. I see the arduino communication light blink but pronterface isn't able to connect.

**Comment by dbenamy** [comment]
http://www.repetier.com/documentation/repetier-host/ looks pretty awesome so far. Might be mac-only.

**Comment by dbenamy** [comment]
I can't get pronterface or repetier to run gcode files although both have their uses for manual control. I like repetier better for almost everything but am still using pronterface to manually send gcode.

There are also potential problems with gcode generating tools in that they spit out gcodes that marlin doesn't understand.

My new plan is to hand write gcode for a simple plate and manually send it by copy pasting through pronterface. This is scalable enough to get us to the point where we can cut warehouse pieces.

We can work out the kinks with the more sophisticated software for a later milestone.

I'll leave this ticket open for the current milestone to figure out some way to stream gcode to the firmware, even if it's a simple command line tool.

**Comment by dbenamy** [comment]
Jesus christ, I've tried about 10 programs and can't get any to work.

**Comment by dbenamy** [comment]
A quick look seems to show that some of these programs assume the firmware will execute the move before responding with carriage return or line feed or whatever. Maybe marlin's responding immediately?
